name: Build and deploy ASP.Net Core app to an Azure Web App

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '7.0.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build with dotnet
        run: dotnet build --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Test with dotnet
        run: dotnet test --configuration Release --no-build

  publish:
    if: "!startsWith(github.ref, 'refs/tags/v')"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: dotnet publish (Dev & Testing)
        run: dotnet publish CustomerManagementService.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish
      - name: Upload artifact for deployment job (Dev & Testing)
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish

  deploy_dev_and_test:
    if: "!startsWith(github.ref, 'refs/tags/v')"
    needs: publish
    runs-on: ubuntu-latest
    environment: 
      name: 'Dev & Testing'
    steps:
      - name: Download artifact for deployment job (Dev & Testing)
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      - name: Apply database migrations (Dev & Testing)
        run: dotnet ef database update --project CustomerManagementService.csproj
        env:
          ConnectionStrings__CustomerDbConnection: ${{ secrets.DEV_CUSTOMER_DB_CONNECTION }}
      - name: Deploy to Azure Web App (Dev & Testing)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.DEV_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.DEV_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
          
  generate_migration_script:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Generate migration script for production
        run: dotnet ef migrations script --idempotent --output ./Data/Migrations/productionMigrations.sql --project CustomerManagementService.csproj
        env:
          ConnectionStrings__CustomerDbConnection: ${{ secrets.PRODUCTION_CUSTOMER_DB_CONNECTION }}
      - name: Upload migration script for manual review
        uses: actions/upload-artifact@v3
        with:
          name: migration-script
          path: ./migrations.sql

  deploy_production:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test, generate_migration_script]
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    steps:
      - name: Download artifact for deployment job (Production)
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.PROD_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.PROD_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
