name: Production Deployment

on:
  push:
    tags:
      - "v*"

env:
  AZURE_WEBAPP_PACKAGE_PATH: "."
  DOTNET_VERSION: "7.0.x"

permissions:
  contents: read

jobs:
  retrieve_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: .net-app

  migrate_database:
    needs: retrieve_artifacts
    runs-on: ubuntu-latest
    environment: 
      name: 'Production'
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Entity Framework Core tools
        run: dotnet tool install --global dotnet-ef --version 7.0.7

      - name: Generate migration script for production
        run: dotnet ef migrations script --idempotent --output ./Data/Migrations/productionMigrations.sql --project CustomerManagementService.csproj

  deploy_dev_and_test:
    needs: migrate_database
    runs-on: ubuntu-latest
    environment: 
      name: 'Production'
    steps:
      - name: Download artifact for deployment job (Production)
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}