name: Production Deployment

on:
  push:
    tags:
      - 'v*'

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '7.0.x'

permissions:
  contents: read

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Verify branch is master
        run: |
          BRANCH_NAME=$(git branch -r --contains tags/${GITHUB_REF##*/} | grep 'origin/master' | head -n 1)
          if [ -z "$BRANCH_NAME" ]; then
            echo "This workflow is only for tags on the master branch."
            exit 78
          fi

      - name: Generate migration script for production
        run: dotnet ef migrations script --idempotent --output ./Data/Migrations/productionMigrations.sql --project CustomerManagementService.csproj
        env:
          ConnectionStrings__CustomerDbConnection: ${{ secrets.PRODUCTION_CUSTOMER_DB_CONNECTION }}

      - name: Upload migration script for manual review
        uses: actions/upload-artifact@v3
        with:
          name: migration-script
          path: ./Data/Migrations/productionMigrations.sql

      - name: dotnet publish (Production)
        run: dotnet publish CustomerManagementService.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish

      - name: Upload artifact for deployment job (Production)
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.PROD_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.PROD_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish
